// Anonymous user tracking utilities

const ANONYMOUS_TOPICS_KEY = 'basicstutor_anonymous_topics';
const ANONYMOUS_COUNT_KEY = 'basicstutor_anonymous_count';

export interface AnonymousTopic {
  id: string;
  slug: string;
  title: string;
  createdAt: string;
}

/**
 * Track a newly generated anonymous topic
 */
export function trackAnonymousTopic(topic: { id: string; slug: string; title: string }): void {
  try {
    const topics = getAnonymousTopics();
    topics.push({
      ...topic,
      createdAt: new Date().toISOString(),
    });
    localStorage.setItem(ANONYMOUS_TOPICS_KEY, JSON.stringify(topics));

    // Increment count
    const count = getAnonymousTopicCount();
    localStorage.setItem(ANONYMOUS_COUNT_KEY, String(count + 1));
  } catch (error) {
    console.error('Failed to track anonymous topic:', error);
  }
}

/**
 * Get all anonymous topics generated by this user
 */
export function getAnonymousTopics(): AnonymousTopic[] {
  try {
    const stored = localStorage.getItem(ANONYMOUS_TOPICS_KEY);
    return stored ? JSON.parse(stored) : [];
  } catch (error) {
    console.error('Failed to get anonymous topics:', error);
    return [];
  }
}

/**
 * Get count of anonymous topics generated
 */
export function getAnonymousTopicCount(): number {
  try {
    const stored = localStorage.getItem(ANONYMOUS_COUNT_KEY);
    return stored ? parseInt(stored, 10) : 0;
  } catch (error) {
    console.error('Failed to get anonymous topic count:', error);
    return 0;
  }
}

/**
 * Clear anonymous tracking (called after migration or sign-up)
 */
export function clearAnonymousTracking(): void {
  try {
    localStorage.removeItem(ANONYMOUS_TOPICS_KEY);
    localStorage.removeItem(ANONYMOUS_COUNT_KEY);
  } catch (error) {
    console.error('Failed to clear anonymous tracking:', error);
  }
}

/**
 * Check if user has reached anonymous limit
 */
export function hasReachedAnonymousLimit(): boolean {
  return getAnonymousTopicCount() >= 1;
}

/**
 * Get anonymous topic IDs for migration
 */
export function getAnonymousTopicIds(): string[] {
  return getAnonymousTopics().map(t => t.id);
}
