/**
 * Curated list of high-search-volume, evergreen, first-principles-friendly
 * topic titles. Fed to server/seed-seo-topics.ts to batch-generate indexable
 * topic pages -- the organic-search growth engine.
 *
 * Selection criteria:
 *  - Real, recurring search demand ("how does X work", "what is Y explained").
 *  - Evergreen (won't go stale like news/trends).
 *  - Genuinely teachable from first principles (the product's whole angle).
 *  - Spread across categories so the Topic Library doesn't look one-note.
 *
 * Extend freely -- just add strings. The runner dedupes against existing
 * slugs, so re-running after adding more only generates the new ones.
 */
export const SEO_TOPICS: string[] = [
  // --- Technology & Computing ---
  "How WiFi Works",
  "How Encryption Works",
  "How Blockchain Works",
  "How GPS Works",
  "How Search Engines Work",
  "How Machine Learning Works",
  "How Neural Networks Work",
  "How Large Language Models Work",
  "How Databases Work",
  "How Compilers Work",
  "How Bitcoin Works",
  "How Cloud Computing Works",
  "How APIs Work",
  "How HTTPS Works",
  "How DNS Works",
  "How Computer Memory Works",
  "How CPUs Work",
  "How Operating Systems Work",
  "How Wireless Charging Works",
  "How Facial Recognition Works",
  "How Recommendation Algorithms Work",
  "How Self-Driving Cars Work",
  "How 5G Works",
  "How Fiber Optic Internet Works",
  "How Two-Factor Authentication Works",
  "How Digital Signatures Work",
  "How Data Compression Works",
  "How Virtual Reality Works",
  "How QR Codes Work",
  "How Streaming Video Works",

  // --- Science & Physics ---
  "How Gravity Works",
  "How Electricity Works",
  "How Magnets Work",
  "How Nuclear Energy Works",
  "How Vaccines Work",
  "How DNA Works",
  "How Photosynthesis Works",
  "How the Immune System Works",
  "How Evolution Works",
  "How Black Holes Work",
  "How the Water Cycle Works",
  "How Sound Works",
  "How Light Works",
  "How Atoms Work",
  "How Lasers Work",
  "How Radioactivity Works",
  "How the Northern Lights Work",
  "How Earthquakes Happen",
  "How Volcanoes Work",
  "How Weather Forecasting Works",
  "How Carbon Dating Works",
  "How the Periodic Table Works",
  "How Chemical Reactions Work",
  "How Genes Are Inherited",
  "How the Big Bang Theory Works",
  "How Tides Work",
  "How Rainbows Form",
  "How Thunder and Lightning Work",

  // --- Finance & Economics ---
  "How Inflation Works",
  "How the Stock Market Works",
  "How Compound Interest Works",
  "How Credit Scores Work",
  "How Mortgages Work",
  "How Taxes Work",
  "How Insurance Works",
  "How Interest Rates Work",
  "How Index Funds Work",
  "How Recessions Happen",
  "How Banks Make Money",
  "How Central Banks Work",
  "How the Bond Market Works",
  "How Options Trading Works",
  "How ETFs Work",
  "How Retirement Accounts Work",
  "How Credit Cards Work",
  "How Exchange Rates Work",
  "How Supply and Demand Works",
  "How Venture Capital Works",
  "How the Federal Reserve Works",
  "How Debt Works",
  "How Budgeting Works",
  "How Dividends Work",

  // --- Health & the Body ---
  "How the Brain Works",
  "How Sleep Works",
  "How Digestion Works",
  "How the Heart Works",
  "How Muscles Grow",
  "How Metabolism Works",
  "How Antibiotics Work",
  "How the Nervous System Works",
  "How Hormones Work",
  "How the Kidneys Work",
  "How Blood Pressure Works",
  "How the Lungs Work",
  "How Pain Works",
  "How Anesthesia Works",
  "How Fasting Affects the Body",
  "How Caffeine Works",
  "How Alcohol Affects the Body",
  "How the Liver Works",
  "How Weight Loss Works",
  "How Vitamins Work",

  // --- Psychology & the Mind ---
  "How Memory Works",
  "How Habits Form",
  "How Motivation Works",
  "How Learning Works",
  "How Cognitive Biases Work",
  "How Emotions Work",
  "How Persuasion Works",
  "How Dreams Work",
  "How Anxiety Works",
  "How Dopamine Works",
  "How Attention Works",
  "How Decision Making Works",
  "How Willpower Works",
  "How First Impressions Work",
  "How the Placebo Effect Works",
  "How Procrastination Works",
  "How Empathy Works",
  "How Confirmation Bias Works",

  // --- Business & Marketing ---
  "How Marketing Works",
  "How Branding Works",
  "How SEO Works",
  "How Advertising Works",
  "How Startups Raise Money",
  "How Supply Chains Work",
  "How Pricing Strategy Works",
  "How Network Effects Work",
  "How Economies of Scale Work",
  "How Product-Market Fit Works",
  "How Subscription Businesses Work",
  "How Franchising Works",
  "How Negotiation Works",
  "How Sales Funnels Work",
  "How Business Models Work",
  "How Competitive Advantage Works",

  // --- Everyday Things ---
  "How Airplanes Fly",
  "How Car Engines Work",
  "How Refrigerators Work",
  "How Solar Panels Work",
  "How Batteries Work",
  "How Microwaves Work",
  "How Air Conditioning Works",
  "How Elevators Work",
  "How Touchscreens Work",
  "How Noise-Cancelling Headphones Work",
  "How Electric Cars Work",
  "How Rockets Work",
  "How Bridges Stay Up",
  "How Nuclear Reactors Work",
  "How Water Filtration Works",
  "How 3D Printing Works",
  "How Cameras Work",
  "How Combustion Engines Work",
  "How Hydroelectric Power Works",
  "How Wind Turbines Work",

  // --- Math & Logic ---
  "What Is Calculus",
  "Understanding Probability",
  "What Is Statistics",
  "Bayes' Theorem Explained",
  "What Is Game Theory",
  "How Prime Numbers Work",
  "What Is Exponential Growth",
  "How Logarithms Work",
  "What Is a Standard Deviation",
  "How Correlation and Causation Differ",
  "What Is Infinity",
  "How Compounding Works in Math",

  // --- Society, History & the World ---
  "How Elections Work",
  "How Democracy Works",
  "How the Legal System Works",
  "How the Electoral College Works",
  "How International Trade Works",
  "How Globalization Works",
  "How Climate Policy Works",
  "How the United Nations Works",
  "How Constitutions Work",
  "How Propaganda Works",
  "How Money Was Invented",
  "How Language Evolves",
  "How Cities Are Planned",
  "How the Justice System Works",

  // --- Learning, Productivity & Self-Improvement ---
  "How Spaced Repetition Works",
  "How Deep Work Works",
  "How Goal Setting Works",
  "How Feedback Loops Work",
  "How First Principles Thinking Works",
  "How Mental Models Work",
  "How Compounding Habits Work",
  "How Focus Works",
  "How Time Management Works",
  "How Critical Thinking Works",
];
