import { useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useInView, useReducedMotion } from "framer-motion";
import { RotateCcw, Sparkles } from "lucide-react";
import { parseVisualSpec, type VisualKind, type VisualSpec } from "@shared/visuals";
import { CompareScene, CycleScene, FlowScene, LayersScene, ScaleScene, TimelineScene } from "./scenes";
import ParticlesScene from "./ParticlesScene";

const KIND_LABEL: Record<VisualKind, string> = {
  particles: "Simulation",
  flow: "Process",
  cycle: "Feedback loop",
  compare: "Comparison",
  timeline: "Timeline",
  scale: "By the numbers",
  layers: "Building blocks",
};

function Scene({ spec, play, instant }: { spec: VisualSpec; play: boolean; instant: boolean }) {
  switch (spec.kind) {
    case "particles": return <ParticlesScene spec={spec} play={play} instant={instant} />;
    case "flow": return <FlowScene spec={spec} play={play} instant={instant} />;
    case "cycle": return <CycleScene spec={spec} play={play} instant={instant} />;
    case "compare": return <CompareScene spec={spec} play={play} instant={instant} />;
    case "timeline": return <TimelineScene spec={spec} play={play} instant={instant} />;
    case "scale": return <ScaleScene spec={spec} play={play} instant={instant} />;
    case "layers": return <LayersScene spec={spec} play={play} instant={instant} />;
  }
}

/** Standalone renderer for a known scene (no fetching) -- also used for previews. */
export function ConceptVisualView({ spec }: { spec: VisualSpec }) {
  // The ref'd element must exist on first render: useInView only starts
  // observing if ref.current is set when its effect runs.
  const ref = useRef<HTMLElement>(null);
  // Low threshold: a scene that's partly on screen but hasn't started yet
  // shows empty frames (labels at opacity 0), which reads as broken.
  const inView = useInView(ref, { once: true, amount: 0.15 });
  const reduceMotion = !!useReducedMotion();
  const [runKey, setRunKey] = useState(0);

  return (
    <figure ref={ref} className="rounded-xl border border-card-border bg-card p-4 sm:p-5" data-testid={`visual-${spec.kind}`}>
      <div className="mb-4 flex items-center justify-between gap-3">
        <span className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">{KIND_LABEL[spec.kind]}</span>
        {!reduceMotion && (
          <button
            type="button"
            onClick={() => setRunKey((k) => k + 1)}
            className="inline-flex items-center gap-1 rounded-md px-1.5 py-0.5 text-xs text-muted-foreground transition-colors hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
            data-testid="button-visual-replay"
          >
            <RotateCcw className="h-3 w-3" />
            Replay
          </button>
        )}
      </div>
      <Scene key={runKey} spec={spec} play={inView} instant={reduceMotion} />
      <figcaption className="mt-4 text-sm leading-relaxed text-muted-foreground">{spec.caption}</figcaption>
    </figure>
  );
}

/**
 * Animated concept visual for one principle. The scene is generated by the
 * server on first request and cached in the DB (server/visuals.ts); anything
 * that isn't a valid scene renders nothing -- a visual is an enhancement, never
 * a blocker for reading the lesson.
 */
export default function ConceptVisual({ principleId }: { principleId: string }) {
  // Only fetch (and, server-side, possibly generate) once the reader is about
  // to reach this principle -- a long lesson shouldn't generate scenes for
  // sections nobody scrolls to. The wrapper div must render from the first
  // pass so useInView has a node to observe.
  const ref = useRef<HTMLDivElement>(null);
  const nearView = useInView(ref, { once: true, margin: "300px 0px" });
  const { data, isLoading } = useQuery<{ spec: unknown; locked?: boolean }>({
    queryKey: ["/api/principles", principleId, "visual"],
    staleTime: Infinity,
    retry: false,
    enabled: nearView,
  });

  const spec = parseVisualSpec(data?.spec);
  const loading = !nearView || isLoading;

  // Only reachable once monetization is on: the server marks visuals Pro-only.
  if (!loading && data?.locked) {
    return (
      <div ref={ref}>
        <a
          href="/pricing"
          className="flex items-center gap-3 rounded-xl border border-dashed border-primary/30 bg-primary/5 px-4 py-3 text-sm transition-colors hover:bg-primary/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
          data-testid="link-visual-upgrade"
        >
          <Sparkles className="h-4 w-4 shrink-0 text-primary" />
          <span>
            <span className="font-medium">Animated visuals are part of Pro.</span>{" "}
            <span className="text-muted-foreground">See every principle in motion.</span>
          </span>
        </a>
      </div>
    );
  }
  if (!loading && !spec) return <div ref={ref} />;
  return (
    <div ref={ref}>
      {loading ? (
        <div className="flex h-36 animate-pulse items-center justify-center rounded-xl border border-card-border bg-muted/30 text-xs text-muted-foreground">
          Drawing a visual…
        </div>
      ) : (
        <ConceptVisualView spec={spec!} />
      )}
    </div>
  );
}
