import { useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useInView, useReducedMotion } from "framer-motion";
import { RotateCcw } from "lucide-react";
import { parseVisualSpec, type VisualKind, type VisualSpec } from "@shared/visuals";
import { CompareScene, CycleScene, FlowScene, LayersScene, ScaleScene, TimelineScene } from "./scenes";
import ParticlesScene from "./ParticlesScene";

const KIND_LABEL: Record<VisualKind, string> = {
  particles: "Simulation",
  flow: "Process",
  cycle: "Feedback loop",
  compare: "Comparison",
  timeline: "Timeline",
  scale: "By the numbers",
  layers: "Building blocks",
};

function Scene({ spec, play, instant }: { spec: VisualSpec; play: boolean; instant: boolean }) {
  switch (spec.kind) {
    case "particles": return <ParticlesScene spec={spec} play={play} instant={instant} />;
    case "flow": return <FlowScene spec={spec} play={play} instant={instant} />;
    case "cycle": return <CycleScene spec={spec} play={play} instant={instant} />;
    case "compare": return <CompareScene spec={spec} play={play} instant={instant} />;
    case "timeline": return <TimelineScene spec={spec} play={play} instant={instant} />;
    case "scale": return <ScaleScene spec={spec} play={play} instant={instant} />;
    case "layers": return <LayersScene spec={spec} play={play} instant={instant} />;
  }
}

/** Standalone renderer for a known scene (no fetching) -- also used for previews. */
export function ConceptVisualView({ spec }: { spec: VisualSpec }) {
  // The ref'd element must exist on first render: useInView only starts
  // observing if ref.current is set when its effect runs.
  const ref = useRef<HTMLElement>(null);
  const inView = useInView(ref, { once: true, amount: 0.35 });
  const reduceMotion = !!useReducedMotion();
  const [runKey, setRunKey] = useState(0);

  return (
    <figure ref={ref} className="rounded-xl border border-card-border bg-card p-4 sm:p-5" data-testid={`visual-${spec.kind}`}>
      <div className="mb-4 flex items-center justify-between gap-3">
        <span className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">{KIND_LABEL[spec.kind]}</span>
        {!reduceMotion && (
          <button
            type="button"
            onClick={() => setRunKey((k) => k + 1)}
            className="inline-flex items-center gap-1 rounded-md px-1.5 py-0.5 text-xs text-muted-foreground transition-colors hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
            data-testid="button-visual-replay"
          >
            <RotateCcw className="h-3 w-3" />
            Replay
          </button>
        )}
      </div>
      <Scene key={runKey} spec={spec} play={inView} instant={reduceMotion} />
      <figcaption className="mt-4 text-sm leading-relaxed text-muted-foreground">{spec.caption}</figcaption>
    </figure>
  );
}

/**
 * Animated concept visual for one principle. The scene is generated by the
 * server on first request and cached in the DB (server/visuals.ts); anything
 * that isn't a valid scene renders nothing -- a visual is an enhancement, never
 * a blocker for reading the lesson.
 */
export default function ConceptVisual({ principleId }: { principleId: string }) {
  const { data, isLoading } = useQuery<{ spec: unknown }>({
    queryKey: ["/api/principles", principleId, "visual"],
    staleTime: Infinity,
    retry: false,
  });

  if (isLoading) {
    return (
      <div className="flex h-36 animate-pulse items-center justify-center rounded-xl border border-card-border bg-muted/30 text-xs text-muted-foreground">
        Drawing a visual…
      </div>
    );
  }

  const spec = parseVisualSpec(data?.spec);
  return spec ? <ConceptVisualView spec={spec} /> : null;
}
